--building view
create view dbo.Building as
SELECT [SchoolYear]
      ,[DistrictCode]
      ,[SchoolCode]
      ,[BuildingCode]
      ,[BuildingName]
      ,[BuildingShortName]
      ,[GradeSpan]
      ,[DepartmentKey]
      ,[BuildingType]
      ,[DistrictKey]
      ,[LocationKey]
      ,[EschoolBuilding]
      ,[County]
      ,[Act]
      ,[EduLevel]
      ,[ProfileLevel]
      ,[Street1]
      ,[Street2]
      ,[City]
      ,[Zip]
      ,[Phone]
      ,[DirectoryInclusion]
      ,[EdDirName]
      ,[Latitude]
      ,[Longitude]
      ,[ChangeAction]
      ,[ChangeTime]
      ,[ChangeUser]
      ,[SeqNum]
      ,[AttendanceConfigurationType]
  FROM [EdOrgs].[Building]

GO

