<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Data\AuthEngineSearchProcMapping.hbm.xml" />
    <None Remove="IdentityManagement\DELSISAssignIDProcMapping.hbm.xml" />
    <None Remove="Data\DELSISSearchProcMapping.hbm.xml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="ApiModel.json">
      <LogicalName>EdFi.Ods.De.Features.IdentityManagement.ApiModel.json</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Data\AuthEngineSearchProcMapping.hbm.xml" />
    <EmbeddedResource Include="Data\DELSISAssignIDProcMapping.hbm.xml" />
    <EmbeddedResource Include="Data\DELSISSearchProcMapping.hbm.xml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NHibernate" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Ed-Fi-ODS\Application\EdFi.Ods.Common\EdFi.Ods.Common.csproj" />
    <ProjectReference Include="..\..\..\Ed-Fi-ODS\Application\EdFi.Ods.Features.IdentityManagement\EdFi.Ods.Features.IdentityManagement.csproj" />
    <ProjectReference Include="..\..\..\Ed-Fi-ODS\Application\EdFi.Ods.Features\EdFi.Ods.Features.csproj" />
  </ItemGroup>

</Project>
