-----Delete Actions

----Delete ClaimsAction
--Select * 
--from dbo.ClaimSetResourceClaimActions ClaimsAction 
--inner join dbo.ClaimSets Claims
--on Claims.ClaimSetId = ClaimsAction.ClaimSetId
--Where  ClaimSetName in ( 'Attendance')
----Where ClaimSetName in ('StudentInformation','StudentCohort','StudentEnrollment')

---- Delete Claimsset
----Delete 
--Select * 
--from dbo.ClaimSets
--Where ClaimSetName in ('StudentInformation','StudentCohort','StudentEnrollment')



  -- Create a claim
INSERT INTO dbo.ClaimSets (ClaimSetName,Application_ApplicationId,IsEdfiPreset,ForApplicationUseOnly) VALUES ('StudentInformation',1,0,0)

-- Resources for the ClaimSets and Actions
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentInformation'), (select ResourceClaimId from ResourceClaims where ResourceName='systemDescriptors'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentInformation'), (select ResourceClaimId from ResourceClaims where ResourceName='LocalEducationAgency'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentInformation'), (select ResourceClaimId from ResourceClaims where ResourceName='School'),2	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentInformation'), (select ResourceClaimId from ResourceClaims where ResourceName='parent'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentInformation'), (select ResourceClaimId from ResourceClaims where ResourceName='person'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentInformation'), (select ResourceClaimId from ResourceClaims where ResourceName='student'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentInformation'), (select ResourceClaimId from ResourceClaims where ResourceName='studentEducationOrganizationAssociation'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentInformation'), (select ResourceClaimId from ResourceClaims where ResourceName='studentParentAssociation'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentInformation'), (select ResourceClaimId from ResourceClaims where ResourceName='types'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentInformation'), (select ResourceClaimId from ResourceClaims where ResourceName='types'),2

INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentInformation'), (select ResourceClaimId from ResourceClaims where ResourceName='types'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentInformation'), (select ResourceClaimId from ResourceClaims where ResourceName='systemDescriptors'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentInformation'), (select ResourceClaimId from ResourceClaims where ResourceName='LocalEducationAgency'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentInformation'), (select ResourceClaimId from ResourceClaims where ResourceName='School'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentInformation'), (select ResourceClaimId from ResourceClaims where ResourceName='parent'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentInformation'), (select ResourceClaimId from ResourceClaims where ResourceName='person'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentInformation'), (select ResourceClaimId from ResourceClaims where ResourceName='student'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentInformation'), (select ResourceClaimId from ResourceClaims where ResourceName='studentEducationOrganizationAssociation'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentInformation'), (select ResourceClaimId from ResourceClaims where ResourceName='studentParentAssociation'),5

INSERT INTO dbo.ClaimSets (ClaimSetName,Application_ApplicationId,IsEdfiPreset,ForApplicationUseOnly) VALUES ('StudentCohort',1,0,0)

INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentCohort'), (select ResourceClaimId from ResourceClaims where ResourceName='systemDescriptors'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentCohort'), (select ResourceClaimId from ResourceClaims where ResourceName='LocalEducationAgency'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentCohort'), (select ResourceClaimId from ResourceClaims where ResourceName='School'),2	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentCohort'), (select ResourceClaimId from ResourceClaims where ResourceName='person'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentCohort'), (select ResourceClaimId from ResourceClaims where ResourceName='student'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentCohort'), (select ResourceClaimId from ResourceClaims where ResourceName='Cohort'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentCohort'), (select ResourceClaimId from ResourceClaims where ResourceName='studentCohortAssociation'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentCohort'), (select ResourceClaimId from ResourceClaims where ResourceName='studentEducationOrganizationAssociation'),2
--INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentCohort'), (select ResourceClaimId from ResourceClaims where ResourceName='studentSchoolAssociation'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentCohort'), (select ResourceClaimId from ResourceClaims where ResourceName='types'),2

INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentCohort'), (select ResourceClaimId from ResourceClaims where ResourceName='types'),5																																					  
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentCohort'), (select ResourceClaimId from ResourceClaims where ResourceName='systemDescriptors'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentCohort'), (select ResourceClaimId from ResourceClaims where ResourceName='LocalEducationAgency'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentCohort'), (select ResourceClaimId from ResourceClaims where ResourceName='School'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentCohort'), (select ResourceClaimId from ResourceClaims where ResourceName='person'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentCohort'), (select ResourceClaimId from ResourceClaims where ResourceName='student'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentCohort'), (select ResourceClaimId from ResourceClaims where ResourceName='Cohort'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentCohort'), (select ResourceClaimId from ResourceClaims where ResourceName='studentCohortAssociation'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentCohort'), (select ResourceClaimId from ResourceClaims where ResourceName='studentEducationOrganizationAssociation'),5
--INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentCohort'), (select ResourceClaimId from ResourceClaims where ResourceName='studentSchoolAssociation'),5

INSERT INTO dbo.ClaimSets (ClaimSetName,Application_ApplicationId,IsEdfiPreset,ForApplicationUseOnly) VALUES ('StudentEnrollment',1,0,0)

INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentEnrollment'), (select ResourceClaimId from ResourceClaims where ResourceName='systemDescriptors'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentEnrollment'), (select ResourceClaimId from ResourceClaims where ResourceName='LocalEducationAgency'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentEnrollment'), (select ResourceClaimId from ResourceClaims where ResourceName='School'),2	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentEnrollment'), (select ResourceClaimId from ResourceClaims where ResourceName='person'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentEnrollment'), (select ResourceClaimId from ResourceClaims where ResourceName='student'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentEnrollment'), (select ResourceClaimId from ResourceClaims where ResourceName='StudentSchoolAssociation'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentEnrollment'), (select ResourceClaimId from ResourceClaims where ResourceName='studentEducationOrganizationResponsibilityAssociation'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentEnrollment'), (select ResourceClaimId from ResourceClaims where ResourceName='calendar'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentEnrollment'), (select ResourceClaimId from ResourceClaims where ResourceName='calendarDate'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentEnrollment'), (select ResourceClaimId from ResourceClaims where ResourceName='graduationPlan'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentEnrollment'), (select ResourceClaimId from ResourceClaims where ResourceName='grade'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentEnrollment'), (select ResourceClaimId from ResourceClaims where ResourceName='types'),2

INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentEnrollment'), (select ResourceClaimId from ResourceClaims where ResourceName='types'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentEnrollment'), (select ResourceClaimId from ResourceClaims where ResourceName='systemDescriptors'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentEnrollment'), (select ResourceClaimId from ResourceClaims where ResourceName='LocalEducationAgency'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentEnrollment'), (select ResourceClaimId from ResourceClaims where ResourceName='School'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentEnrollment'), (select ResourceClaimId from ResourceClaims where ResourceName='person'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentEnrollment'), (select ResourceClaimId from ResourceClaims where ResourceName='student'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentEnrollment'), (select ResourceClaimId from ResourceClaims where ResourceName='StudentSchoolAssociation'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentEnrollment'), (select ResourceClaimId from ResourceClaims where ResourceName='studentEducationOrganizationResponsibilityAssociation'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentEnrollment'), (select ResourceClaimId from ResourceClaims where ResourceName='calendar'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentEnrollment'), (select ResourceClaimId from ResourceClaims where ResourceName='calendarDate'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentEnrollment'), (select ResourceClaimId from ResourceClaims where ResourceName='graduationPlan'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='StudentEnrollment'), (select ResourceClaimId from ResourceClaims where ResourceName='grade'),5

--Responsibility schools Authorization
insert into [dbo].[ClaimSetResourceClaimActionAuthorizationStrategyOverrides] (ClaimSetResourceClaimActionId, AuthorizationStrategyId)
select ClaimSetResourceClaimActionId, (select AuthorizationStrategyId from AuthorizationStrategies where AuthorizationStrategyName='RelationshipsWithStudentsOnly' and Application_ApplicationId=1)   from ClaimSetResourceClaimActions 
where  ResourceClaimId in (select ResourceClaimId from ResourceClaims where ResourceName='studentEducationOrganizationResponsibilityAssociation') 
and ClaimSetId in (select ClaimsetID from ClaimSets where ClaimSetName='StudentEnrollment')


INSERT INTO dbo.ClaimSets (ClaimSetName,Application_ApplicationId,IsEdfiPreset,ForApplicationUseOnly) VALUES ('TeachingNLearning',1,0,0)

INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='systemDescriptors'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='LocalEducationAgency'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='School'),2	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='person'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='student'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='StudentSchoolAssociation'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='Session'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='Section'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='Classperiod'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='Location'),2	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='Course'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='courseOffering'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='studentSectionAssociation'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='calendar'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='calendarDate'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='grade'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='cIPCourse'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='gradingPeriod'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='types'),2

INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='types'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='systemDescriptors'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='LocalEducationAgency'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='School'),5	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='person'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='student'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='StudentSchoolAssociation'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='Session'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='Section'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='Classperiod'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='Location'),5	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='Course'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='courseOffering'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='studentSectionAssociation'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='calendar'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='calendarDate'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='grade'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='cIPCourse'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='TeachingNLearning'), (select ResourceClaimId from ResourceClaims where ResourceName='gradingPeriod'),5

INSERT INTO dbo.ClaimSets (ClaimSetName,Application_ApplicationId,IsEdfiPreset,ForApplicationUseOnly) VALUES ('Staff',1,0,0)

INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Staff'), (select ResourceClaimId from ResourceClaims where ResourceName='systemDescriptors'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Staff'), (select ResourceClaimId from ResourceClaims where ResourceName='LocalEducationAgency'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Staff'), (select ResourceClaimId from ResourceClaims where ResourceName='School'),2	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Staff'), (select ResourceClaimId from ResourceClaims where ResourceName='person'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Staff'), (select ResourceClaimId from ResourceClaims where ResourceName='staff'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Staff'), (select ResourceClaimId from ResourceClaims where ResourceName='staffSchoolAssociation'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Staff'), (select ResourceClaimId from ResourceClaims where ResourceName='StaffEducationOrganizationAssignmentAssociation'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Staff'), (select ResourceClaimId from ResourceClaims where ResourceName='Program'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Staff'), (select ResourceClaimId from ResourceClaims where ResourceName='StaffProgramAssociation'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Staff'), (select ResourceClaimId from ResourceClaims where ResourceName='StaffSectionAssociation'),2	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Staff'), (select ResourceClaimId from ResourceClaims where ResourceName='StaffCohortAssociation'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Staff'), (select ResourceClaimId from ResourceClaims where ResourceName='types'),2

INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Staff'), (select ResourceClaimId from ResourceClaims where ResourceName='types'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Staff'), (select ResourceClaimId from ResourceClaims where ResourceName='systemDescriptors'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Staff'), (select ResourceClaimId from ResourceClaims where ResourceName='LocalEducationAgency'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Staff'), (select ResourceClaimId from ResourceClaims where ResourceName='School'),5	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Staff'), (select ResourceClaimId from ResourceClaims where ResourceName='person'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Staff'), (select ResourceClaimId from ResourceClaims where ResourceName='staff'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Staff'), (select ResourceClaimId from ResourceClaims where ResourceName='staffSchoolAssociation'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Staff'), (select ResourceClaimId from ResourceClaims where ResourceName='StaffEducationOrganizationAssignmentAssociation'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Staff'), (select ResourceClaimId from ResourceClaims where ResourceName='Program'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Staff'), (select ResourceClaimId from ResourceClaims where ResourceName='StaffProgramAssociation'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Staff'), (select ResourceClaimId from ResourceClaims where ResourceName='StaffSectionAssociation'),5	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Staff'), (select ResourceClaimId from ResourceClaims where ResourceName='StaffCohortAssociation'),5


INSERT INTO dbo.ClaimSets (ClaimSetName,Application_ApplicationId,IsEdfiPreset,ForApplicationUseOnly) VALUES ('Attendance',1,0,0)

INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Attendance'), (select ResourceClaimId from ResourceClaims where ResourceName='systemDescriptors'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Attendance'), (select ResourceClaimId from ResourceClaims where ResourceName='LocalEducationAgency'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Attendance'), (select ResourceClaimId from ResourceClaims where ResourceName='School'),2	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Attendance'), (select ResourceClaimId from ResourceClaims where ResourceName='person'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Attendance'), (select ResourceClaimId from ResourceClaims where ResourceName='Student'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Attendance'), (select ResourceClaimId from ResourceClaims where ResourceName='Section'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Attendance'), (select ResourceClaimId from ResourceClaims where ResourceName='studentSectionAssociation'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Attendance'), (select ResourceClaimId from ResourceClaims where ResourceName='studentSectionAttendanceEvent'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Attendance'), (select ResourceClaimId from ResourceClaims where ResourceName='studentSchoolAttendanceEvent'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Attendance'), (select ResourceClaimId from ResourceClaims where ResourceName='types'),2

INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Attendance'), (select ResourceClaimId from ResourceClaims where ResourceName='types'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Attendance'), (select ResourceClaimId from ResourceClaims where ResourceName='systemDescriptors'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Attendance'), (select ResourceClaimId from ResourceClaims where ResourceName='LocalEducationAgency'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Attendance'), (select ResourceClaimId from ResourceClaims where ResourceName='School'),5	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Attendance'), (select ResourceClaimId from ResourceClaims where ResourceName='person'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Attendance'), (select ResourceClaimId from ResourceClaims where ResourceName='Student'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Attendance'), (select ResourceClaimId from ResourceClaims where ResourceName='Section'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Attendance'), (select ResourceClaimId from ResourceClaims where ResourceName='studentSectionAssociation'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Attendance'), (select ResourceClaimId from ResourceClaims where ResourceName='studentSectionAttendanceEvent'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Attendance'), (select ResourceClaimId from ResourceClaims where ResourceName='studentSchoolAttendanceEvent'),5

INSERT INTO dbo.ClaimSets (ClaimSetName,Application_ApplicationId,IsEdfiPreset,ForApplicationUseOnly) VALUES ('Discipline',1,0,0)
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='systemDescriptors'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='LocalEducationAgency'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='School'),2	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='person'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='Student'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='Staff'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='DisciplineIncident'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='DisciplineAction'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='StudentDisciplineIncidentAssociation'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='StaffDisciplineIncidentAssociation'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='studentDisciplineIncidentBehaviorAssociation'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='studentDisciplineIncidentNonOffenderAssociation'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='restraintEvent'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='restraintSeclusion'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='allegedBullyingVictim'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='types'),2

INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='types'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='systemDescriptors'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='LocalEducationAgency'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='School'),5	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='person'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='Student'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='Staff'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='DisciplineIncident'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='DisciplineAction'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='StudentDisciplineIncidentAssociation'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='StaffDisciplineIncidentAssociation'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='studentDisciplineIncidentBehaviorAssociation'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='studentDisciplineIncidentNonOffenderAssociation'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='restraintEvent'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='restraintSeclusion'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Discipline'), (select ResourceClaimId from ResourceClaims where ResourceName='allegedBullyingVictim'),5

INSERT INTO dbo.ClaimSets (ClaimSetName,Application_ApplicationId,IsEdfiPreset,ForApplicationUseOnly) VALUES ('504Program',1,0,0)
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='504Program'), (select ResourceClaimId from ResourceClaims where ResourceName='systemDescriptors'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='504Program'), (select ResourceClaimId from ResourceClaims where ResourceName='LocalEducationAgency'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='504Program'), (select ResourceClaimId from ResourceClaims where ResourceName='School'),2	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='504Program'), (select ResourceClaimId from ResourceClaims where ResourceName='person'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='504Program'), (select ResourceClaimId from ResourceClaims where ResourceName='Student'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='504Program'), (select ResourceClaimId from ResourceClaims where ResourceName='Program'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='504Program'), (select ResourceClaimId from ResourceClaims where ResourceName='Student504ProgramAssociation'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='504Program'), (select ResourceClaimId from ResourceClaims where ResourceName='types'),2

INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='504Program'), (select ResourceClaimId from ResourceClaims where ResourceName='types'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='504Program'), (select ResourceClaimId from ResourceClaims where ResourceName='systemDescriptors'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='504Program'), (select ResourceClaimId from ResourceClaims where ResourceName='LocalEducationAgency'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='504Program'), (select ResourceClaimId from ResourceClaims where ResourceName='School'),5	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='504Program'), (select ResourceClaimId from ResourceClaims where ResourceName='person'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='504Program'), (select ResourceClaimId from ResourceClaims where ResourceName='Student'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='504Program'), (select ResourceClaimId from ResourceClaims where ResourceName='Program'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='504Program'), (select ResourceClaimId from ResourceClaims where ResourceName='Student504ProgramAssociation'),5

INSERT INTO dbo.ClaimSets (ClaimSetName,Application_ApplicationId,IsEdfiPreset,ForApplicationUseOnly) VALUES ('SpecialEducationProgram',1,0,0)
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='SpecialEducationProgram'), (select ResourceClaimId from ResourceClaims where ResourceName='systemDescriptors'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='SpecialEducationProgram'), (select ResourceClaimId from ResourceClaims where ResourceName='LocalEducationAgency'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='SpecialEducationProgram'), (select ResourceClaimId from ResourceClaims where ResourceName='School'),2	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='SpecialEducationProgram'), (select ResourceClaimId from ResourceClaims where ResourceName='person'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='SpecialEducationProgram'), (select ResourceClaimId from ResourceClaims where ResourceName='Student'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='SpecialEducationProgram'), (select ResourceClaimId from ResourceClaims where ResourceName='Program'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='SpecialEducationProgram'), (select ResourceClaimId from ResourceClaims where ResourceName='StudentSpecialEducationProgramAssociation'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='SpecialEducationProgram'), (select ResourceClaimId from ResourceClaims where ResourceName='types'),2

INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='SpecialEducationProgram'), (select ResourceClaimId from ResourceClaims where ResourceName='types'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='SpecialEducationProgram'), (select ResourceClaimId from ResourceClaims where ResourceName='systemDescriptors'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='SpecialEducationProgram'), (select ResourceClaimId from ResourceClaims where ResourceName='LocalEducationAgency'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='SpecialEducationProgram'), (select ResourceClaimId from ResourceClaims where ResourceName='School'),5	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='SpecialEducationProgram'), (select ResourceClaimId from ResourceClaims where ResourceName='person'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='SpecialEducationProgram'), (select ResourceClaimId from ResourceClaims where ResourceName='Student'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='SpecialEducationProgram'), (select ResourceClaimId from ResourceClaims where ResourceName='Program'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='SpecialEducationProgram'), (select ResourceClaimId from ResourceClaims where ResourceName='StudentSpecialEducationProgramAssociation'),5

INSERT INTO dbo.ClaimSets (ClaimSetName,Application_ApplicationId,IsEdfiPreset,ForApplicationUseOnly) VALUES ('EnglishLearner',1,0,0)
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='EnglishLearner'), (select ResourceClaimId from ResourceClaims where ResourceName='systemDescriptors'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='EnglishLearner'), (select ResourceClaimId from ResourceClaims where ResourceName='LocalEducationAgency'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='EnglishLearner'), (select ResourceClaimId from ResourceClaims where ResourceName='School'),2	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='EnglishLearner'), (select ResourceClaimId from ResourceClaims where ResourceName='person'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='EnglishLearner'), (select ResourceClaimId from ResourceClaims where ResourceName='Student'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='EnglishLearner'), (select ResourceClaimId from ResourceClaims where ResourceName='Program'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='EnglishLearner'), (select ResourceClaimId from ResourceClaims where ResourceName='StudentLanguageInstructionProgramAssociation'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='EnglishLearner'), (select ResourceClaimId from ResourceClaims where ResourceName='types'),2

INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='EnglishLearner'), (select ResourceClaimId from ResourceClaims where ResourceName='types'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='EnglishLearner'), (select ResourceClaimId from ResourceClaims where ResourceName='systemDescriptors'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='EnglishLearner'), (select ResourceClaimId from ResourceClaims where ResourceName='LocalEducationAgency'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='EnglishLearner'), (select ResourceClaimId from ResourceClaims where ResourceName='School'),5	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='EnglishLearner'), (select ResourceClaimId from ResourceClaims where ResourceName='person'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='EnglishLearner'), (select ResourceClaimId from ResourceClaims where ResourceName='Student'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='EnglishLearner'), (select ResourceClaimId from ResourceClaims where ResourceName='Program'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='EnglishLearner'), (select ResourceClaimId from ResourceClaims where ResourceName='StudentLanguageInstructionProgramAssociation'),5

INSERT INTO dbo.ClaimSets (ClaimSetName,Application_ApplicationId,IsEdfiPreset,ForApplicationUseOnly) VALUES ('HealthRecords',1,0,0)
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='HealthRecords'), (select ResourceClaimId from ResourceClaims where ResourceName='systemDescriptors'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='HealthRecords'), (select ResourceClaimId from ResourceClaims where ResourceName='LocalEducationAgency'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='HealthRecords'), (select ResourceClaimId from ResourceClaims where ResourceName='School'),2	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='HealthRecords'), (select ResourceClaimId from ResourceClaims where ResourceName='person'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='HealthRecords'), (select ResourceClaimId from ResourceClaims where ResourceName='Student'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='HealthRecords'), (select ResourceClaimId from ResourceClaims where ResourceName='MedicalAlert'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='HealthRecords'), (select ResourceClaimId from ResourceClaims where ResourceName='MedicalOfficeVisit'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='HealthRecords'), (select ResourceClaimId from ResourceClaims where ResourceName='MedicalReferralFollowUp'),2	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='HealthRecords'), (select ResourceClaimId from ResourceClaims where ResourceName='MedicalScreening'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='HealthRecords'), (select ResourceClaimId from ResourceClaims where ResourceName='medicationBox'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='HealthRecords'), (select ResourceClaimId from ResourceClaims where ResourceName='personMedicalAlert'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='HealthRecords'), (select ResourceClaimId from ResourceClaims where ResourceName='personImmunization'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='HealthRecords'), (select ResourceClaimId from ResourceClaims where ResourceName='types'),2

INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='HealthRecords'), (select ResourceClaimId from ResourceClaims where ResourceName='types'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='HealthRecords'), (select ResourceClaimId from ResourceClaims where ResourceName='systemDescriptors'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='HealthRecords'), (select ResourceClaimId from ResourceClaims where ResourceName='LocalEducationAgency'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='HealthRecords'), (select ResourceClaimId from ResourceClaims where ResourceName='School'),5	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='HealthRecords'), (select ResourceClaimId from ResourceClaims where ResourceName='person'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='HealthRecords'), (select ResourceClaimId from ResourceClaims where ResourceName='Student'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='HealthRecords'), (select ResourceClaimId from ResourceClaims where ResourceName='MedicalAlert'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='HealthRecords'), (select ResourceClaimId from ResourceClaims where ResourceName='MedicalOfficeVisit'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='HealthRecords'), (select ResourceClaimId from ResourceClaims where ResourceName='MedicalReferralFollowUp'),5	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='HealthRecords'), (select ResourceClaimId from ResourceClaims where ResourceName='MedicalScreening'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='HealthRecords'), (select ResourceClaimId from ResourceClaims where ResourceName='medicationBox'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='HealthRecords'), (select ResourceClaimId from ResourceClaims where ResourceName='personMedicalAlert'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='HealthRecords'), (select ResourceClaimId from ResourceClaims where ResourceName='personImmunization'),5

INSERT INTO dbo.ClaimSets (ClaimSetName,Application_ApplicationId,IsEdfiPreset,ForApplicationUseOnly) VALUES ('Graduation',1,0,0)
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Graduation'), (select ResourceClaimId from ResourceClaims where ResourceName='systemDescriptors'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Graduation'), (select ResourceClaimId from ResourceClaims where ResourceName='LocalEducationAgency'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Graduation'), (select ResourceClaimId from ResourceClaims where ResourceName='School'),2	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Graduation'), (select ResourceClaimId from ResourceClaims where ResourceName='person'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Graduation'), (select ResourceClaimId from ResourceClaims where ResourceName='student'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Graduation'), (select ResourceClaimId from ResourceClaims where ResourceName='StudentSchoolAssociation'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Graduation'), (select ResourceClaimId from ResourceClaims where ResourceName='graduationPlan'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Graduation'), (select ResourceClaimId from ResourceClaims where ResourceName='studentAcademicRecord'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Graduation'), (select ResourceClaimId from ResourceClaims where ResourceName='PostSecondaryInstitution'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Graduation'), (select ResourceClaimId from ResourceClaims where ResourceName='PostSecondaryEvent'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Graduation'), (select ResourceClaimId from ResourceClaims where ResourceName='postSecondaryDetail'),2
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Graduation'), (select ResourceClaimId from ResourceClaims where ResourceName='types'),2

INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Graduation'), (select ResourceClaimId from ResourceClaims where ResourceName='types'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Graduation'), (select ResourceClaimId from ResourceClaims where ResourceName='systemDescriptors'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Graduation'), (select ResourceClaimId from ResourceClaims where ResourceName='LocalEducationAgency'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Graduation'), (select ResourceClaimId from ResourceClaims where ResourceName='School'),5	 
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Graduation'), (select ResourceClaimId from ResourceClaims where ResourceName='person'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Graduation'), (select ResourceClaimId from ResourceClaims where ResourceName='student'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Graduation'), (select ResourceClaimId from ResourceClaims where ResourceName='StudentSchoolAssociation'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Graduation'), (select ResourceClaimId from ResourceClaims where ResourceName='graduationPlan'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Graduation'), (select ResourceClaimId from ResourceClaims where ResourceName='studentAcademicRecord'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Graduation'), (select ResourceClaimId from ResourceClaims where ResourceName='PostSecondaryInstitution'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Graduation'), (select ResourceClaimId from ResourceClaims where ResourceName='PostSecondaryEvent'),5
INSERT INTO ClaimSetResourceClaimActions (ClaimSetId, ResourceClaimId, ActionId) select (select ClaimSetId from ClaimSets where  ClaimSetName='Graduation'), (select ResourceClaimId from ResourceClaims where ResourceName='postSecondaryDetail'),5