INSERT INTO [de].[SchoolExtension]([SchoolId],[AttendanceConfigurationCategoryDescriptorId] ,[UnitCountException])
     VALUES
(100610,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(100611,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(100612,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(100615,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(100616,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(100618,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(100620,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(100621,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),1),
(100622,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(100625,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),1),
(100626,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(100628,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(100629,null,null),
(100630,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(130632,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(130634,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(130635,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(130636,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(130638,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(130640,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(130642,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(130644,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(130646,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(130648,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(130649,null,null),
(130650,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(130653,null,null),
(130655,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(130656,null,null),
(150658,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(150659,null,null),
(150660,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(150661,null,null),
(150662,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(150663,null,null),
(150664,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(150665,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(150669,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(160752,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(160753,null,null),
(160756,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(160781,null,null),
(160782,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(160783,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(170710,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(170712,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(170718,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(170720,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(170721,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(170722,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(170724,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(170726,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(170728,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(180668,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(180670,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(180672,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(180673,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(180675,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(180678,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(180679,null,null),
(230759,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(230760,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(230761,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(230762,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(230763,null,null),
(230764,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(230766,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(230768,null,null),
(240680,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(240681,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(240682,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(240684,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(240685,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(240686,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(240687,null,null),
(240688,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(240696,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(290010,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(290011,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(290013,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(290014,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(290016,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(290017,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(290018,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(290020,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(290021,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(290022,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(290023,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(290024,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(290027,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(290028,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(290029,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(290032,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(290505,null,null),
(290507,null,null),
(290508,null,null),
(310108,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(310110,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(310112,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(310124,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(310128,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(310130,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(310132,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(310150,null,null),
(310151,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(310156,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(310170,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(310176,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(310178,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(310180,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(310190,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(310194,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(310196,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(310510,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(320203,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(320240,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(320242,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(320244,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(320246,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(320248,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(320250,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(320252,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(320254,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(320256,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(320260,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(320261,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(320264,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(320266,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(320270,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(320271,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(320274,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(320276,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(320280,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(320282,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(320284,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(320286,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(320290,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(320292,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(320294,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(320516,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(320526,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(320530,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(330310,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330312,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330314,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330318,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330320,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330321,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330322,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330324,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330326,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330327,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330330,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330332,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330334,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330339,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330350,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330351,null,null),
(330352,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330354,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330356,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330358,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330362,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330372,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330374,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330376,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330390,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330392,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330394,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330512,null,null),
(330534,null,null),
(330535,null,null),
(330537,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),1),
(330538,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),1),
(330540,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(330544,null,null),
(330545,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(340410,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(340412,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(340418,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(340420,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(340422,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(340427,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(340432,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(340450,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(340456,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(340470,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(340474,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(340476,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(340490,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(340514,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(340515,null,null),
(340522,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(340523,null,null),
(350775,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'T'),null),
(350776,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(350779,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'T'),null),
(350780,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'T'),null),
(360689,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(360690,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(360691,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(360692,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(360732,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(360734,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(360736,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(360738,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(360740,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(360741,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(360742,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(360743,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(360745,null,null),
(360746,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(360748,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(360749,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(360750,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(360758,null,null),
(370730,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(370733,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(370737,null,null),
(370739,null,null),
(380026,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(380044,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(380051,null,null),
(380066,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(380080,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(380539,null,null),
(380541,null,null),
(390652,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(400770,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'T'),null),
(680567,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(690568,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(690569,null,null),
(700295,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'T'),null),
(710570,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(720571,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(740573,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(740980,null,null),
(760575,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(770576,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),1),
(779576,null,null),
(790578,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(800579,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(820581,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(850584,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(860585,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(860586,null,null),
(860591,null,null),
(870586,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(880587,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),1),
(884587,null,null),
(890588,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(890589,null,null),
(890590,null,null),
(920543,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(96044040,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(96054045,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(96064050,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'H'),null),
(96065050,null,null),
(96074055,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(96094065,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(96114075,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null),
(96124080,(SELECT DescriptorId FROM edfi.Descriptor WHERE Namespace = 'uri://doe.k12.de.us/AttendanceConfigurationCategoryDescriptor' and codevalue = 'P'),null)
GO

update edfi.EducationOrganization set Discriminator='edfi.School' where EducationOrganizationId in (882587,860589,96114175)
go